### ISSUE TITLE
gopls has advanced to version 0.4.1, snap: still at 0.1.7

### ISSUE THREAD

**Issue by lightyear15** [alexmurray/gopls-snap#1]
https://pkg.go.dev/golang.org/x/tools/gopls@v0.4.1?tab=doc

Not sure how snap works, yet I'd say there might be an issue at tracking versions
can you please update it so it can pick latest version?
thanks

**Comment by alexmurray** [comment]
Thanks for the heads up - I had thought I was subscribed to get notified of new releases but apparently not - I am now though and will make sure to trigger a rebuild on future releases. I have just retriggered a new build so expect something soon. Then it should be just a `snap refresh gopls` . Note however I can't seem to easily extract the upstream version number correctly when building at the moment so this is likely to just be a git commit hash as the version number for now.
